//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryEntities : DbContext
    {
        public libraryEntities()
            : base("name=libraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NhaXuatBan> NhaXuatBans { get; set; }
        public DbSet<Phat> Phats { get; set; }
        public DbSet<PhieuMuon> PhieuMuons { get; set; }
        public DbSet<PhieuThuTien> PhieuThuTiens { get; set; }
        public DbSet<Sach> Saches { get; set; }
        public DbSet<Sach_copy> Sach_copy { get; set; }
        public DbSet<TacGia> TacGias { get; set; }
        public DbSet<TheDocGia> TheDocGias { get; set; }
        public DbSet<TheLoai> TheLoais { get; set; }
    }
}
