//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaXuatBan
    {
        public NhaXuatBan()
        {
            this.Sach_copy = new HashSet<Sach_copy>();
        }
    
        public int nxb_id { get; set; }

        [Display(Name = "Publisher")]
        public string Ten { get; set; }
    
        public virtual ICollection<Sach_copy> Sach_copy { get; set; }
    }
}
