//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phat
    {
        public Phat()
        {
            this.PhieuThuTiens = new HashSet<PhieuThuTien>();
        }
    
        public int phat_id { get; set; }
        public Nullable<int> SoNgayTre { get; set; }
        public Nullable<decimal> SoTienPhat { get; set; }
        public int docgia_id { get; set; }
        public int pm_id { get; set; }
    
        public virtual TheDocGia TheDocGia { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual ICollection<PhieuThuTien> PhieuThuTiens { get; set; }
    }
}
