//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public PhieuMuon()
        {
            this.Phats = new HashSet<Phat>();
        }
    
        public int pm_id { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public int docgia_id { get; set; }
        public int copy_id { get; set; }
    
        public virtual ICollection<Phat> Phats { get; set; }
        public virtual Sach_copy Sach_copy { get; set; }
        public virtual TheDocGia TheDocGia { get; set; }
    }
}
