//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuTien
    {
        public int thutien_id { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<int> phat_id { get; set; }
    
        public virtual Phat Phat { get; set; }
    }
}
