//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        public Sach()
        {
            this.Sach_copy = new HashSet<Sach_copy>();
            this.TacGias = new HashSet<TacGia>();
        }
    
        public int sach_id { get; set; }

        [Display(Name = "Book name")]
        public string TenSach { get; set; }

        [Display(Name = "Description")]
        public string ThongTin { get; set; }
        public int theloai_id { get; set; }

        public virtual Sach_copy Sach_Copy { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual ICollection<Sach_copy> Sach_copy { get; set; }
        public virtual ICollection<TacGia> TacGias { get; set; }
    }
}
