//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach_copy
    {
        public Sach_copy()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int copy_id { get; set; }
        public Nullable<System.DateTime> NamXuatBan { get; set; }

        [Display(Name = "Amount")]
        public Nullable<int> SoLuong { get; set; }
        public string pdf_link { get; set; }
        public Nullable<bool> is_removed { get; set; }
        public Nullable<int> sach_id { get; set; }
        public Nullable<int> nxb_id { get; set; }
        public string image { get; set; }
    
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
