//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement_Website
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TheDocGia
    {
        public TheDocGia()
        {
            this.Phats = new HashSet<Phat>();
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int docgia_id { get; set; }

        [Display(Name = "Reader name")]
        public string Ten { get; set; }

        [Display(Name = "Date created")]
        public System.DateTime NgayLapThe { get; set; }

        [Display(Name = "Date of birth")]
        public System.DateTime NgaySinh { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string Password { get; set; }
        public string LoaiDG { get; set; }
    
        public virtual ICollection<Phat> Phats { get; set; }
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
